<div class="mt-3">
   <?php if (!is_null($_SESSION['alert'])){
    ?>
    <div class="alert alert-<?php echo $_SESSION['alert']; ?>">
        <?php echo $_SESSION['message']; ?>
    </div>
    <?php 
    }
    ?>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
      Tambah Data
    </button>
    <table class="table table-bordered table-hover mt-2">
        <thead class="thead-light">
        <tr>
            <th width="1">#</th>
            <th>Provinsi</th>
            <th>Jumlah</th>
            <th width="200">Aksi</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if ($covid->count() > 0) { 
            $i = 1;
             foreach ($covid as $cov) { ?>
            <tr>
                <td><?php echo $i++; ?></td>
                <td><?php echo $cov->province; ?></td>
                <td><?php echo $cov->covid->summary; ?></td>
                <td>
                        <a href="index/edit/<?=$cov->covid->id?>">
                            <button type="button" class="btn btn-warning">
                                Edit 
                            </button>
                        </a>

                        <a href="index/delete/<?=$cov->covid->id?>">
                            <button type="button" class="btn btn-danger" onclick="return confirm('Anda Yakin?');">
                                Delete 
                            </button>
                        </a>
                </td>
            </tr>
        <?php } 
        ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="5">Total Data Covid: <?php echo $covid->count(); ?> Data</td>
        </tr>
        </tfoot>
             <?php }?>
    </table>
    <div id="chartContainer" class="mt-5">
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <form method="post" action="index/save" class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Tambah Data Covid</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <div class="form-group">
                <label for="province">Provinsi</label>
                <select name="province" id="province" class="form-control" required>
                    <option value="">Pilih Provinsi</option>
                    <?php
                        foreach($province as $prov) { ?>
                            <option value="<?=$prov->id?>"><?=$prov->province?></option>
                        <?php }
                    ?>
                </select>
            </div>
            <div class="form-group">
                <label for="summary">Jumlah</label>
                <input type="number" name="summary" id="summary" class="form-control" min="1" required/>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
        <button type="submit" class="btn btn-primary">Simpan</button>
      </div>
    </div>
  </div>
</div>


<?php
unset($_SESSION['alert']);
unset($_SESSION['message']);
$_SESSION['alert'] = null;
$_SESSION['message'] = null;
?>